language: rust
rust:
  - 1.31.0

before_script:
  - rustup component add rustfmt-preview

cache:
  directories:
    - ./target

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo test
  - cargo rustdoc -- --document-private-items 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: target/doc
  target_branch: gh-pages
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never